name: Wallet Monitor - Daily Mailer


on:
  push:
    branches:
      - main
#  schedule:
#    - cron: '30 11 * * *' # Everyday at 11:30


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run script
        env:
            SENDER_EMAIL_ADDRESS: ${{ vars.SENDER_EMAIL_ADDRESS }}
            SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
            ZONDA_API_KEY: ${{ secrets.ZONDA_API_KEY }}
            ZONDA_API_SECRET: ${{ secrets.ZONDA_API_SECRET }}
            MARKET_CURRENCY: ${{ vars.MARKET_CURRENCY }}
        run: |
            echo "Executing main.py..."
            pushd app
            python main.py
